# --- BACKGROUND ---
background {
    monitor =
    color = rgb(000000) 
}

general {
    hide_cursor = true
}

animations {
    enabled = true
    # A very smooth, slow curve
    bezier = slowEase, 0.25, 0.1, 0.25, 1.0
    
    # fadeIn: 1 (on), 15 (speed/duration), curve
    animation = fadeIn, 1, 15, slowEase
    animation = inputFieldFade, 1, 15, slowEase
}
# --- THE SCRIPT OUTPUT ---
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/info.sh
    color = rgb(ffffff)         
    font_size = 19
    font_family = Material Design Icons
    
    position = -45, -22   
    halign = right
    valign = top
}

# --- TIME ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(666666) 
    font_size = 400
    font_family = sans-serif # Change to your preferred system font (e.g., Inter, Roboto)
    position = 0, 10
    halign = center
    valign = center
    shadow_passes = 0
}


# --- PASSWORD INPUT FIELD ---
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 1 # Keeping it minimal to match your aesthetic
    
    # Inner and Outer Colors
    inner_color = rgb(161616) # $bg-surface-alt
    outer_color = rgba(255, 255, 255, 0.12) # $border-thin
    font_color = rgb(ffffff) # $text-main
    
    # Dot Styling
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    
    # Text and Behavior
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    
    # Authentication States
    check_color = rgb(5e355e) # $bg-active (Your custom purple for checking state)
    fail_color = rgb(cc3333) # Red for failure (Matches the ThinkPad red dot)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(ffffff) # $bg-hover for capslock warning
    
    # Positioning & Borders
    position = 0, 50
    halign = center
    valign = bottom
    rounding = 12 # $radius-md
}

