# --- BACKGROUND ---
background {
    monitor =
    path = screenshot 
    color = rgba(00, 00, 00, 0.8)
    blur_passes = 2
}

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = slowEase, 0.25, 0.1, 0.25, 1.0
    
    animation = fadeIn, 1, 15, slowEase
    animation = inputFieldFade, 1, 15, slowEase
}
# --- THE SCRIPT OUTPUT ---
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/info.sh
    color = rgb(ffffff)         
    font_size = 19
    font_family = Material Design Icons
    
    position = -45, -22   
    halign = right
    valign = top
}

# --- TIME ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(666666) 
    font_size = 400
    font_family = sans-serif 
    position = 0, 10
    halign = center
    valign = center
    shadow_passes = 0
}


input-field {
    monitor =
    size = 280, 50
    outline_thickness = 1     
    inner_color = rgb(161616)
    outer_color = rgba(255, 255, 255, 0.12)
    font_color = rgb(ffffff)     
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    
    check_color = rgb(5e355e)
    fail_color = rgb(cc3333)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(ffffff)
    position = 0, 50
    halign = center
    valign = bottom
    rounding = 12
}

