# --- BACKGROUND ---
background {
    monitor =
    path = /$HOME/.config/hypr/loock.png
    color = rgb(00000000)
}

general {
    hide_cursor = true
}

animations {
    enabled = true
}

label {
    monitor =
    text = <span weight="900"> 󰍁 </span>
    color = rgb(000000)
    font_size = 50
    
    position = 0, -30
    halign = center
    valign = top
}

# --- CLOCK LAYER (Behind Image) ---

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgb(ffffff)
    font_size = 160
    font_family = JetBrainsMono NFM
    
    position = 0, 100
    halign = center
    valign = bottom
}

# --- THE SCRIPT OUTPUT ---
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/info.sh
    color = rgb(ffffff)         
    font_size = 19
    font_family = Material Design Icons
    
    position = 0, 30   
    halign = center
    valign = bottom
}

# --- INPUT FIELD ---
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 0
    inner_color =   rgba(00, 00, 00, 0)
    outer_color = rgba(255, 255, 255, 0)
    font_color = rgb(ffffff)     
    dots_size = 2.5
    dots_spacing = 0.25
    dots_center = true
    
    fade_on_empty = false
    placeholder_text = <i></i>
    hide_input = false
    
    check_color = rgb(5e355e)
    fail_color = rgb(ff0000)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(ffffff)
    position = 0, 80
    halign = center
    valign = bottom
    rounding = 12
    zindex = 2
}
