
[preferred]
default=gtk
# Use GNOME for the actual recording and the settings it needs
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome
org.freedesktop.impl.portal.Settings=gnome;gtk
